### ISSUE TITLE
Header Should be Static

### ISSUE THREAD

**Issue by adityakishore25** [PranavBarthwal/cosmoXplore#242] opened 2024-05-23 14:27 UTC
### Describe the feature

The website header is currently not static. To enhance the user experience, the header should remain fixed at the top of the page as users scroll down. This will improve navigation and accessibility.

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/107037851/43e3ccf9-33a6-41e8-9ef2-b283eed8981f)

@surajvast1 could you assign this enhancement to me. I would love to work on it under GSSoC'24.

### Would you like to work on this issue?

None

**Comment by surajvast1** [comment] 2024-05-23 14:32
Take it  @adityakishore25  . Agar galti huuii naaaaa ,sitting in next room only 😂

**Comment by adityakishore25** [comment] 2024-05-23 14:34
@surajvast1 kindly increase the level, I'll do it after the exam :)

**Comment by surajvast1** [comment] 2024-05-23 14:36
Some one take this

**Comment by surajvast1** [comment] 2024-05-23 14:38
THe issue is Open someone take it

**Comment by karthickkumarsm** [comment] 2024-05-23 17:20
can you assign this issue to me?

**Comment by Ketanop321** [comment] 2024-05-23 17:51
I can make the navbar fixed when someone scrolls  down to the page . Please assign to me @adityakishore25 , this will be great learning for me🤗

**Comment by surajvast1** [comment] 2024-05-27 12:25
@Ketanop321  adityakishore25 is not with us, should i assign you ?

**Comment by Ketanop321** [comment] 2024-05-27 12:30
> @Ketanop321 adityakishore25 is not with us, should i assign you ?

yes i am able to fix this , so you can surely assign it to me

**Closed** 2024-05-27 19:05 UTC
Labels: enhancement, gssoc, level1
